server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    com.netflix.discovery: fatal
    com.netflix.eureka: fatal