server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:bookdb
  sql:
    init:
      mode: always
      schema-locations: classpath*:schema.sql
      data-locations: classpath*:data.sql
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

logging:
  level:
    root: info
