spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookStore

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.otus.andrk.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: error
    com.github.cloudyrock.mongock.runner: info
    ru.otus.andrk: debug
