book-app:
  default-lang: en
  enable-bubu: true
  bubu-factor: 10

server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  messages:
    basename: messages
  datasource:
    url: jdbc:h2:mem:bookdb
  sql:
    init:
      mode: always
      schema-locations: classpath*:database/schema.sql
      data-locations: classpath*:database/data.sql
      encoding: UTF-8
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

logging:
  level:
    root: error
    #ru.otus.andrk: info
    ru.otus.andrk: debug
    org.springframework.boot.web.embedded.tomcat: info

