spring:
  data:
    mongodb:
        host: localhost
        port: 0
        database: hw14
  datasource:
    url: jdbc:h2:mem:hw14
    username: test
    password: test
  h2:
    console:
      enabled: true
      path: /h2-console
