app:
  api-server:
    url: http://localhost:8082
  i18n:
    default-lang: en
    message-bundle: messages

server:
  port: 8080

spring:
  application:
    name: front-app
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: false

logging:
  level:
    root: error
    ru.otus.andrk: debug
    org.springframework.boot.web.embedded.tomcat: info