app:
  i18n:
    default-lang: en
    message-bundle: messages

server:
  port: 8080

spring:
  application:
    name: front-app
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false


management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    allow-redirects: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: false

resilience4j:
  circuitbreaker:
    metrics:
      enabled: true
    configs:
      default:
        slidingWindowType: count_based
        ignore-exceptions:
          - ru.otus.andrk.exception.ProcessedException
    instances:
      libraryServiceBreaker:
        base-config: default
  retry:
    configs:
      default:
        maxAttempts: 10
        fail-after-max-attempts: true
        waitDuration: 2000
        ignore-exceptions:
          - ru.otus.andrk.exception.ProcessedException
    instances:
      libraryServiceBreaker:
        base-config: default


logging:
  level:
    root: error
    ru.otus.andrk: debug
    org.springframework.boot.web.embedded.tomcat: info


